workflows:
  default-workflow:
    name: Default workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    # Specify path to the app folder like this
    working_directory: ios/path-to-your-project